# Generated by Django 3.1.4 on 2021-01-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210110_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
