# Generated by Django 3.1.4 on 2021-01-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210110_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_Name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otro'), ('4', 'Ladron')], max_length=1, verbose_name='Cargo'),
        ),
    ]
